_format_version: "3.0"
_transform: true

services:
  - name: auth
    url: http://host.docker.internal:3000

  - name: property
    url: http://host.docker.internal:3001

  - name: booking
    url: http://host.docker.internal:3002

  - name: payment
    url: http://host.docker.internal:3003

routes:
  - name: auth-route
    service: auth
    protocols:
      - http
      - https
    paths:
      - /users
    strip_path: false

  #  property (sem JWT)
  - name: property-public-available
    service: property
    protocols:
      - http
      - https
    paths:
      - /properties/available
    methods:
      - GET
    strip_path: false

  - name: property-public-search
    service: property
    protocols:
      - http
      - https
    paths:
      - /properties/search
    methods:
      - GET
    strip_path: false

  #  property (com JWT)
  - name: property-route
    service: property
    protocols:
      - http
      - https
    paths:
      - /properties
    methods:
      - GET
      - POST
      - PUT
      - DELETE
    strip_path: false

  - name: booking-route
    service: booking
    protocols:
      - http
      - https
    paths:
      - /bookings
    strip_path: false

  - name: payment-route
    service: payment
    protocols:
      - http
      - https
    paths:
      - /payments
    strip_path: false

consumers:
  - username: cognito-users
    jwt_secrets:
      - algorithm: RS256
        key: "xAI2ocCj9PSkPQwqF/5IEbfuhNTItJ0zykAUOldDO4o="
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu3k6LFDhgCOY+otfVWVE
          jzTWF0Ruz3P6SygRq183AZreoHzMX+cQv87g4U2mVZ2FK9r9DXhRt0rISW4UJw3J
          jBK1v/E0bdoOXC845lY/w1bX1OWzYat4iVUG6i1T5I/RNvZUAq1bPwPAY9Qic3Ht
          9dvHX4pI424tvi6GF0oIEZ6H4arHIbp1Alsb7XJtPQlg4Uo5sCm5NW8YkBKpfMit
          SnE0N+ly85jBViOt+CBK89+GPGII6AAeSJuoT9/CJxh27vfabHJwg3j5sI7e6y6p
          WxlyOjena9rq4tOezCByVykIJMCrkvlJKAkOZRgY87yoyjdp+cSUiAcWXHLIS0Ie
          dQIDAQAB
          -----END PUBLIC KEY-----

      - algorithm: RS256
        key: "yslzEgegtzs2uCCneI50SpYfXKqxWhqhqbukB5ZRLbQ="
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp2INKa4KP1m/BZYx1578
          LW85SyBx6AGp2hPdxFiluyBDQQx2m24VNLl3evvwHbHS3GvFOBztlAdk/QRpkFL1
          dh++wPXIP2F2ebjbHOgfg4HrWgNWJeLbAp7T+gFeVAu9QXpFW81zxhRa8Be3+4gp
          aKhG1X18R4Lswx9wqh90EFeq+n7lTfhL9jWhGlnBiQDz3+IKjLUNBLDI02RZsGFB
          ILKxr+CbqtoLp+NqEe2EctEAQtsiVfKOrK0RAPhO4cgzfWgVLVZIGB9ukooyJKBF
          IPhtiA7Il1+94meZ4IeA37nrfBz11T3L9ekVa17h9KKGr8p4oCCeng7qD+l/oH1k
          WwIDAQAB
          -----END PUBLIC KEY-----

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - Origin

  - name: jwt
    route: property-route
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
      header_names:
        - authorization

  - name: jwt
    route: booking-route
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
      header_names:
        - authorization

  - name: jwt
    route: payment-route
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
      header_names:
        - authorization
