services:
  property-db:
    image: bitnami/postgresql
    container_name: airbnb_property_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property_db
    ports:
      - "5433:5432"
    volumes:
      - property_postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  property-service:
    build: .
    container_name: property-service
    depends_on:
      - property-db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@property-db:5432/property_db
    networks:
      - microservices-network
    ports:
      - "3001:3001"

volumes:
  property_postgres_data:

networks:
  microservices-network:
    external: true
