name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  pulumi:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache-dependency-path: infra/pulumi/go.sum

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Pulumi up
        uses: pulumi/actions@v6
        with:
          command: up
          work-dir: ./infra/pulumi
          stack-name: carlosEA28/deploy-bnb/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  migrate:
    needs: pulumi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache-dependency-path: infra/pulumi/go.sum

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Pega endpoints do RDS
        id: rds
        run: |
          cd infra/pulumi
          AUTH=$(pulumi stack output db-endpoint-auth-service --stack carlosEA28/deploy-bnb/dev)
          BOOKING=$(pulumi stack output db-endpoint-booking-service --stack carlosEA28/deploy-bnb/dev)
          PAYMENT=$(pulumi stack output db-endpoint-payment-service --stack carlosEA28/deploy-bnb/dev)
          PROPERTY=$(pulumi stack output db-endpoint-propety-service --stack carlosEA28/deploy-bnb/dev)
          echo "AUTH_DB=$AUTH" >> $GITHUB_OUTPUT
          echo "BOOKING_DB=$BOOKING" >> $GITHUB_OUTPUT
          echo "PAYMENT_DB=$PAYMENT" >> $GITHUB_OUTPUT
          echo "PROPERTY_DB=$PROPERTY" >> $GITHUB_OUTPUT
          echo "--- DEBUG ---"
          echo "AUTH: $AUTH"
          echo "BOOKING: $BOOKING"
          echo "PAYMENT: $PAYMENT"
          echo "PROPERTY: $PROPERTY"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Migrate — auth-service
        run: |
          npm ci
          npx prisma migrate deploy --schema=prisma/schema.prisma
        working-directory: services/auth-service
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ steps.rds.outputs.AUTH_DB }}/auth_db

      - name: Debug booking
        run: |
          ls -la
          cat package-lock.json | head -5
        working-directory: services/booking-service

      - name: Migrate — booking-service
        run: |
          npm ci
          npx prisma migrate deploy --schema=prisma/schema.prisma
        working-directory: services/booking-service
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ steps.rds.outputs.BOOKING_DB }}/booking_db

      - name: Migrate — property-service
        run: |
          npm ci
          npx prisma migrate deploy --schema=prisma/schema.prisma
        working-directory: services/propety-service
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ steps.rds.outputs.PROPERTY_DB }}/property_db

      - name: Migrate — payment-service
        run: |
          npm ci
          npx prisma migrate deploy --schema=prisma/schema.prisma
        working-directory: services/payment-service
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.DB_PASSWORD }}@${{ steps.rds.outputs.PAYMENT_DB }}/payment_db
