name: Tests

on:
  pull_request:
  push:
  workflow_call:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: services/auth-service/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: services/auth-service
      - name: Generate Prisma client
        run: npx prisma generate --schema=prisma/schema.prisma
        working-directory: services/auth-service
      - name: Run tests
        run: npm test
        working-directory: services/auth-service

  test-booking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
        working-directory: services/booking-service
      - run: npm test
        working-directory: services/booking-service

  test-property:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
        working-directory: services/propety-service
      - run: npm test
        working-directory: services/propety-service

  test-payment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Run tests
        run: go test -v ./...
        working-directory: services/payment-service
